### ISSUE TITLE
Re-Sync everytime is normal usage? - Question

### ISSUE THREAD

**Issue by kiralikbeyin** [google-home/smarthome-washer#28]
@Fleker 
When i sync the Google Home screen, after sometime (max a few hours) i have to re-sync the Google Home screen by pulling down the screen.
If i dont make sync:
````
(orginal code)
app.onQuery(async (body) => {
  const {requestId} = body;
  const payload = {
    devices: {},
  };
  const queryPromises = [];
  for (const input of body.inputs) {
    for (const device of input.payload.devices) {
      const deviceId = device.id;
      queryPromises.push(queryDevice(deviceId)
        .then((data) => {
          // Add response to device payload
          payload.devices[deviceId] = data;
        }
      ));
    }
  }

...

which goes to

(orginal code)
const queryDevice = async (deviceId) => {
  const data = await queryFirebase(deviceId);
  return {
    on: data.on,
    isPaused: data.isPaused,
    isRunning: data.isRunning,
    currentRunCycle: [{
      currentCycle: 'rinse',
      nextCycle: 'spin',
      lang: 'en',
    }],
    currentTotalRemainingTime: 1212,
    currentCycleRemainingTime: 301,
    currentModeSettings: {
      load: data.load,
    },
    currentToggleSettings: {
      Turbo: data.turbo,
    },
  };
}
````
doesnt remember my email (username) so device is not responding.

Re-Sync everytime is normal usage for Google Home?

note my app published.

**Comment by Fleker** [comment]
That seems odd. Did you make any changes to the OAuth flow? By default there should only be one user, so there wouldn't be an email to forget.

**Comment by Fleker** [comment]
What do you mean by having your app "published"?

**Comment by kiralikbeyin** [comment]
@Fleker published i mean my app was approved and it is on production. I made a lot of code changes.
Maybe it is a bad idea, washer-start as a template to use for production?

My db structure is like:
https://xxx.firebaseio.com/users/myEmail@gmail-com/devices/uniqueDeviceId-1
https://xxx.firebaseio.com/users/myEmail@gmail-com/devices/uniqueDeviceId-2
...

https://xxx.firebaseio.com/users/otherUserEmail@gmail-com/devices/uniqueDeviceId-1
https://xxx.firebaseio.com/users/otherUserEmail@gmail-com/devices/uniqueDeviceId-2
https://xxx.firebaseio.com/users/otherUserEmail@gmail-com/devices/uniqueDeviceId-3
...

If i dont make sync before turn on-off switch i saw things in fb like:
FBROOT/devices/uniqueDeviceId-3/states/on/true


**I have a more basic problem which I have to solve first.**

(This is related with linking so i am not opening a new issue)

Followed https://medium.com/google-developers/authenticating-smart-home-actions-for-the-google-assistant-with-auth0-b6fda3d2ee3d

Everything is fine for first login. If i unlink and try login again auth0 auto completed (i think) and return back to Google Home quicly and i cant ese my devices like my first login.

1-Delete user from auth0.com works but not a solution.

2-This problem occurs only with real clientID and secret which taken from gcp. 
auth0.com keys are only for dev tests. https://auth0.com/docs/connections/social/google
https://github.com/googlecodelabs/smarthome-washer/issues/23#issuecomment-529252137


3-I changed JWT Expiration to only 5 seconds but nothing happened.

4-Another solution in auth0.com which i dont want use is Multi-factor Authentication:
Push via Auth0 Guardian & One-time Password. It is a little hard for a user and it needs another screen like phone or pc to read a QR code with your phone...

5-Another ugly developer solution (yes it works like a first signup and links your devices) is below, slow down page transitions:

I found a way to usb debuging with chrome:
Check this first : https://github.com/googlecodelabs/smarthome-washer/issues/26#issuecomment-513470314
GH goes to auth0.com and quickly returns back. Before returning to "Add devices" screen if you hold your finger in a 100-500ms you will see "Return App" screen and it will stay on this page. Open it with chrome. Maybe this can help someone..

I will try to kill session - if no session: no logged user so everytime screen will work like a new signup.


I am not good with oauth2 but trying... Is there a simple way?

**Comment by Fleker** [comment]
So if you don't re-sync everytime, and you get a request, do you not see an authorization token in your header? Is this an issue affecting every user of your service?

**Comment by kiralikbeyin** [comment]
Yes it is for every user.

I see auth token for every request. I got email when user syncs and i store in a global variable : var userEmail

When a turn on-off switch request comes i see 
```
 "authorization": "Bearer CnMsCmQQxmW-ogQtYAOmtiQO1D4p8-__",
```

Maybe i miss something? How can i understand user email from this token?

**Comment by Fleker** [comment]
Your OAuth system should have a way to associate an access token to a user email. If you're using Auth0, you can use a function like

```
const getEmail = async (headers) => {
  const accessToken = headers.authorization.substr(7);
  const {email} = await auth0.getProfile(accessToken);
  return email;
}
```

**Comment by kiralikbeyin** [comment]
@Fleker Thanks.

I am using this code in the script for sync but forgot... 

I will try on-off tomorrow without sync.

**Comment by kiralikbeyin** [comment]
@Fleker I just open GH and devices are not responding. There is no log in FB functions. 
My last action was 11 hours ago.

I tried sync devices by pulling down the screen but devices are still not responing.
Where can i find a log?

**Comment by Fleker** [comment]
There's some issue in the auth connection. However, the OAuth issues aren't logged with enough clarity as to what they mean. I'm not sure that it's particularly the fault of Auth0.

**Comment by kiralikbeyin** [comment]
Please gide an alternatife for auth0.com which workshop with GH?

**Comment by javiercuellar73** [comment]
I think the problem is the token has expired and "refresh_token" is not working with auth0.
Look log in GoogleCloudPlatform, Stackdriver, Logs.... function "Google Assistant Action" and see if you see "OPEN_AUTH_FAILURE"....

I have that problem and can't find a solution.

**Comment by shannonhwu-google** [comment]
Apologies for the delayed response here. 

@kiralikbeyin Just to confirm, yes, having to re-sync each time is abnormal behavior. However, we weren't able to reproduce your issue and the codelab code is working. 

For more information on account linking, please reference our developer's site: https://developers.home.google.com/cloud-to-cloud/primer/account-linking.

If this issue is still occurring, please use the [Issue Tracker](https://developers.home.google.com/cloud-to-cloud/support#report_a_bug_or_request_new_features) so we can help you resolve in detail. Thanks.
