### ISSUE TITLE
Cannot read property 'isPaused' of undefined

### ISSUE THREAD

**Issue by LindaLawton** [google-home/smarthome-washer#32]
> TypeError: Cannot read property 'isPaused' of undefined
>     at queryFirebase (/srv/index.js:116:41)
>     at <anonymous>
>     at process._tickDomainCallback (internal/process/next_tick.js:229:7)

**Comment by devunwired** [comment]
Can you clarify which step of the codelab you encountered this error?
Or do you see this issue deploying the `washer-done` solution project?

**Comment by shannonhwu-google** [comment]
Closing the issue as last discussion was 2020. Please reopen if necessary.
