### ISSUE TITLE
Deployed application running failed since some changes of firebase database api?

### ISSUE THREAD

**Issue by dqisme** [google-home/smarthome-washer#36]
When I followed your steps and deploy the application in the firebase, it gives me the message like this:
```
@firebase/database: FIREBASE FATAL ERROR: Cannot parse Firebase url. Please use https://<YOUR FIREBASE>.firebaseio.com
```

Would you consider keeping this repository up-to-date, so that people won't say google home sucks (even for developer)?

**Comment by kevin-netgear** [comment]
I got this error
Error: It looks like you haven't created a Realtime Database instance in this project before. Please run firebase init database to create your default Realtime Database instance.

**Comment by proppy** [comment]
@dqisme did you remplace `YOUR FIREBASE` with your firebase instance name?

**Comment by shb** [comment]
@proppy There is no app configuration anywhere in the repo and certainly no place where a `<YOUR FIREBASE>` should be replaced with anything. It is not mentioned in the step-by-step tutorial.

**Comment by alesbani** [comment]
try upgrade SDK_VERSION from 7.13.1 to 8.10.1
in  /washer-start/public/index.html
works for me.

```
  <script src="/__/firebase/8.10.1/firebase-app.js"></script>
  <script src="/__/firebase/8.10.1/firebase-auth.js"></script>
  <script src="/__/firebase/8.10.1/firebase-database.js"></script>
  <script src="/__/firebase/init.js"></script>
```

**Comment by shannonhwu-google** [comment]
This issue is unreproducible now, so I will close out the issue, please feel free to open if needed.
