### ISSUE TITLE
Upgrade to Blaze plan in firebase deploy command

### ISSUE THREAD

**Issue by aks1709** [google-home/smarthome-washer#37]
When I deploy firebase, I get a error like below.

Your project must be on the Blaze (pay-as-you-go) plan to complete this command. Required API cloudbuild.googleapis.com can't be enabled until the upgrade is complete. To upgrade, visit the following URL:

It is really required to upgrade to blaze plan for just connecting Google Home app with Firebase Database?

**Comment by proppy** [comment]
The billing requirements comes from `Cloud Functions for Firebase`, the codelab does have a note about this in https://codelabs.developers.google.com/codelabs/smarthome-washer#1:
```
This project uses Cloud Functions for Firebase, which requires you to associate a billing account with your project. Actions projects do not create a billing account by default. See Create a new billing account for more information.
```

For more details about Cloud Functions for Firebase free tier, see:
https://cloud.google.com/functions/pricing#free_tier

**Comment by LeventeBotos** [comment]
Hiya,

I've just had this issue resolved. you have a .firebase directory, in that there is a functions dir. Delete it. 
This was the problem. At least for me.

**Comment by shannonhwu-google** [comment]
@LeventeBotos We were not able to reproduce this behavior.
Before successful deployment, the .firebase directory nor the functions dir inside doesn't exist. So, deleting should work, but following the steps on the codelab shouldn't result in a functions dir.
Not making any changes to the codelab at this time.

**Comment by Abdelhafid01** [comment]
It doesn't work for me, i have deleted all the files in .firebase directory but still have the issue that tell to upgrade the plan to Blaze to complete, is it necessary to enable artifactregistry.googleapis.com ?

**Comment by shannonhwu-google** [comment]
Yes, please see the note on the codelab which says "If you have not yet configured billing for your project, you will need to upgrade to the Blaze (pay-as-you-go) plan for [Firebase Functions](https://console.firebase.google.com/project/) to finish deploying your project."

You will have to upgrade the plan regardless, not due to any issue.
