### ISSUE TITLE
Improve Logs readability

### ISSUE THREAD

**Issue by pierredelisle7** [google-home/smarthome-washer#39]
In the codelab documentation at https://codelabs.developers.google.com/codelabs/smarthome-washer/#5, the log for a smarthome request shows an “info” log with the details of the Request object as shown below:

<img width="631" alt="Screen Shot 2021-02-08 at 9 34 09 AM" src="https://user-images.githubusercontent.com/628732/107258576-d154df80-69f0-11eb-9018-8c5eb560ef6b.png">

However, when running the codelab, the request object is not shown:

<img width="743" alt="LogWithoutDebug" src="https://user-images.githubusercontent.com/628732/107258709-fb0e0680-69f0-11eb-89b5-59d782e7b8c1.png">

Digging into the code, it appears that option “debug” must be enabled when instantiating smarthome, as shown below:

`
const app = smarthome({
  debug: true
});
`

However, after this is done, one will quickly notice readability issues of the log entries. Unfortunately, one log message appears with multiple log entries as shown below: 

<img width="654" alt="LogWithDebug" src="https://user-images.githubusercontent.com/628732/107258944-43c5bf80-69f1-11eb-8edf-11d03a887142.png">

This appears to be caused by the fact that the smarthome node.js client library (actions-on-goole-nodejs) uses console.log(). These readability issues are mentioned in the Cloud Functions documentation “Write and view logs”. It is suggested the following:

> With console.log, you may notice issues in the readability of your logs when migrating from the Node.js 8 runtime to Node.js 10 or 12. To work around this temporarily, add the following library to your functions:
        require("firebase-functions/lib/logger/compat");
 The recommended long-term solution for migrating to Node.js 10 or 12 is to refactor code to use the logger SDK.

The codelab does not use console.log() so this does not apply here. Rather, it is the use of console.log() in the node.js client library that is the issue.

Given that, would be great to do the following:

- update documentation to clarify that app option “debug” must be set to true to see request and header details when the smarthome endpoint is called. 
- Ideally, the node.js smarthome client could be configured to use the cloud functions logging mechanism. For that,  I’ll follow up with an issue at https://github.com/actions-on-google/actions-on-google-nodejs.

**Comment by proppy** [comment]
Another possibility woudl be to mark `debug: false` and implement more specific logging in the codelab itself as we recently did in the sample:
https://github.com/actions-on-google/smart-home-nodejs/commit/903be16ef5ab8c0796dca0a6b36919d014a255ba

**Comment by pierredelisle** [comment]
Agree that this is another possibility.

Personally, I think it would be great if all log messages (debug, info, warn, error) coming from the smart-home nodejs client library worked well with firebase cloud functions, or any other log console for that matter. Making the loggers configurable makes this possible without requiring client applications to add additional log messages to obtain information that is already reported by the smart-home nodejs client library. 

I just filed this [issue](https://github.com/actions-on-google/actions-on-google-nodejs/issues/413) and the associated [PR](https://github.com/actions-on-google/actions-on-google-nodejs/pull/414) @ actions-on-google-nodejs for one possible approach.

**Comment by proppy** [comment]
In the shorterm, may be we should just turn `debug: true` for this codelab and import `require("firebase-functions/lib/logger/compat");` ?

**Comment by pierredelisle** [comment]
Obsolete at this point.
