### ISSUE TITLE
Google Home Mini always reply "Sorry, it looks like the washer is unavailable right now"

### ISSUE THREAD

**Issue by JasmineWang0123** [google-home/smarthome-washer#45]
I am able to deploy the cloud fulfillment to the firebase. 
I am able to add the device-washer to the Google Home app. 
I am able to turn on /off the washer at Google Home app graph UI. There is On/off button at Washer. The changes can be reflected on firebase realtime database
However when I try to use voice command to Google Home Mini or Google Home app like, "Turn on washer " or "Turn on living room washer". Google Home Mini always reply "Sorry, it looks like the washer is unavailable right now"
This is also happen when I try to type the command in Google Home app.

Information:
1. The firewall for AP and desktop are turned off.
2. Same wifi has been connected with Phone, desktop, Google Home Mini one.
3. System Firmware: 250118. cast firmware version: 1.54.250118. Android Google Home app: 2.39.1.7 
4. same owner account for Google Home mini, Google Home app, desktop Chrome.

To fix this, I have try out 
1. Link and relink washer to google home app and put under living room, Google Home mini is located at same living room . 
2. Use owner account, same wifi 2.4GHz with my desktop and google home mini and phone 
3. Speak "Sync devices " to google home mini, Google Home mini reply as "Got it, sync devices <project id>" 
4. Reboot Google Home mini 
5. Factory reset, plug out the power cable for more than 1 min, unlink and relink washer , try voice control to Google Home app or  Google Home mini" turn on living room washer" or "turn on washer, get reply as ""Sorry, it looks like the washer is unavailable right now" 
6. For my Home router, there is no special setting for enable/ disable AP isolation.

**Comment by shannonhwu-google** [comment]
This issue is unreproducible after testing with Google Home mini (2nd gen). Will close out for now, but please reopen as necessary.
