### ISSUE TITLE
[Step 3] Eslint: Unexpected token =>

### ISSUE THREAD

**Issue by jeffmur** [google-home/smarthome-washer#46]
I could not deploy with ```firebase deploy``` due to a rudimentary issue with ESLint. Note: this is not an error with the published code, however, a versioning issue with ESLint and ecmaVersion. \
I installed [@babel/eslint-parser](https://www.npmjs.com/package/@babel/eslint-parser) Version 7.16.0 to the node modules via 

```bash
$ npm install @babel/preset-env --save-dev 
```
The patch.txt file {[patch.txt](https://github.com/googlecodelabs/smarthome-washer/files/7464404/patch.txt)}

Shows the following changes: 

1. Addition of: parser: "@babel/eslint-parser" in .eslintrc.js line 2
2. Addition of "no-unused-vars": "warn" in .eslintrc.js line 14
3. Removal of .eslintrc.json
4. Addition of babel.config.json

Finally, the resulting configuration should resemble:

![eslint-compile](https://user-images.githubusercontent.com/32208127/139962657-3edf8f6c-ab7f-4740-bd39-8bbeb14a99fc.png)

To go further you can remove the warnings with "off" instead of "warn" explained [here](https://eslint.org/docs/user-guide/configuring/rules).

**Comment by raymondchlin** [comment]
It has been updated and resolved.
