### ISSUE TITLE
Devices shown as loading for around 10-15 seconds in Google Home app

### ISSUE THREAD

**Issue by maxakash** [google-home/smarthome-washer#47]
Everything seems to work fine but my Google Home shows my device state as "loading" for around 10-11 seconds every time I open the app. Same thing is observed in Home Control in my Nest Hub 2.

But devices from other vendors like sinric pro take only 1-2 seconds to show their device state in Google Home.

@Fleker Please help as I am using this code on my several ESP8266 with Google Nest Hub to control my home. And I have to wait for 10-15 seconds every time to even turn on the lights.

**Comment by shannonhwu-google** [comment]
Hi @maxakash,

The issue is unreproducible, so I will close out the issue for now, please feel free to open if needed.
