### ISSUE TITLE
Database not created when configuring the Firebase project

### ISSUE THREAD

**Issue by puloxtor** [google-home/smarthome-washer#51]
When initializing the Firebase project with on firebase version 11.20.0
`firebase init`

The options for the features provided differ from the example.

Example: **Database: Configure Firebase Realtime Database and deploy rules**
Appears:  **Realtime Database: Configure a security rules file for Realtime Database and (optionally) provision default instance**

next step should be the following prompt:

? It seems like you haven't initialized Realtime Database in your project yet. Do you want to set it up?
Yes

but the option doesn't appear, this leads to the database not being created in the project console.

**Comment by MagnusJohansson** [comment]
Same problem here. It's astonishing to me that nobody from Google has even bothered to reply to this bug, nor fixed it, since it was reported 3 months ago.

**Comment by shannonhwu-google** [comment]
Hi @puloxtor @MagnusJohansson,

Please refer to the updated codelab documentation with this fixed. Thanks for your input!
