### ISSUE TITLE
switch to esm

### ISSUE THREAD

**Issue by jimmywarting** [google-home/smarthome-washer#52]
- Update NodeJS version to something newer like 18+ that have fetch built in and other goodies
- Update package json to have type module:
```json
  "type": "module",
  "engines": {
    "node": "18"
  },
```
- change eslint parser optino to something like
```json
    "parserOptions": {
      "ecmaVersion": 2022,
      "sourceType": "module"
    },
```
in public html: use `type="module`
```html
<script src="main.js" type="module"></script>
```

fyi, i think it's better to keep all exports at the bottom, it's easier to refactor such code and easiely see what kind of stuff is being exported

so removing `exports.reportstate = `  stuff and just declaring it as a variable and then later at the bottom.
then it's just a matter of just doing one small change
```diff
- module.exports = {
+ export {
   everything
 }
```
it's also way more easier to see what is getting exported.

**Comment by GoroAkai** [comment]
Thanks for the valuable information.
I am also struggling to make this source compatible with esmodule. How did you handle the following code? 
exports.smarthome = functions.https.onRequest(app);

**Comment by shannonhwu-google** [comment]
Hi @jimmywarting, our team reviewed your suggestions and discovered that the codelab could not deploy successfully.

Specifically, the suggested changes to update Node.js to version 18, set "type" to "module" in package.json, and modify the ESLint parser options caused this deployment error "Error: Functions codebase could not be analyzed successfully. It may have a syntax or runtime error."

Also, "ecmaVersion": 2022 is an invalid ecmaVersion for the current codelab eslint version (^6.3.0").

As the codelab is up to date, if this is a specific note for others working with compatibility for esm, I will close the thread for now.

Please feel free to re-open if you have more context for a feature request or more follow up.
