### ISSUE TITLE
No functions deployed from the codelab

### ISSUE THREAD

**Issue by haran090** [google-home/smarthome-washer#53]
The firebase.json file is in the repo does not contain an entry for functions and therefore no functions are being deployed. I have seen other guides/implementations use a functions blob in the firebase.json file. Has this been removed on purpose? Or am I missing something

**Comment by GinyWang** [comment]
Fix this issue by adding the entry for functions: [PR #54](https://github.com/google-home/smarthome-washer/pull/54).
